// Code generated by "stringer -type Position"; DO NOT EDIT.

package anchor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[After-0]
	_ = x[Before-1]
}

const _Position_name = "AfterBefore"

var _Position_index = [...]uint8{0, 5, 11}

func (i Position) String() string {
	if i < 0 || i >= Position(len(_Position_index)-1) {
		return "Position(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Position_name[_Position_index[i]:_Position_index[i+1]]
}
